### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by imnotplastina** [Enerjizer3000/laboratory_bot#1]
https://github.com/Enerjizer3000/laboratory_bot/blob/28ff851e1a3a2b143586a0f6cdb962600e408a21/main.py#L16

Тут у тебя ошибка, исправь мурадик

**Comment by Enerjizer3000** [comment]
> https://github.com/Enerjizer3000/laboratory_bot/blob/28ff851e1a3a2b143586a0f6cdb962600e408a21/main.py#L16
> 
> Тут у тебя ошибка, исправь мурадик

Этот код работает, там нет ошибок

**Comment by Aspir01** [comment]
Здравствуйте, Enerjizer2004. Да согласен, на 126 строке у вас ошибка.
